[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_crowdfunding = "9mpE1jK1k2V2X9KZW269pPE34j39wNwX3aQHejeHgKuQ"
[programs.devnet]
solana_crowdfunding = "9mpE1jK1k2V2X9KZW269pPE34j39wNwX3aQHejeHgKuQ"

[registry]
url = "https://api.apr.dev"

# [provider]
# cluster = "localnet"
# wallet = "./keypair/keypair.json"

[provider]
cluster = "devnet"
wallet = "/Users/yashsharma/.config/solana/id.json"




[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
tdd = "watch -p '**/*.ts' -p '**/*.rs' -c 'anchor test'"